version: "3"
services:
  postgres:
    image: postgres:14
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  technicaltest:
    build:
      context: .
    user: root
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - postgres
    environment:
      DJANGO_SETTINGS_MODULE: technicaltest.settings
    volumes:
      - .:/app

volumes:
  postgres-data:
