# Generated by Django 4.1.2 on 2023-02-01 17:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone should have the following format: '+xxxxxxxxx'.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
