# Generated by Django 4.1.2 on 2023-02-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meetings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('data', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('status', models.CharField(choices=[('completed', 'completed'), ('todo', 'todo'), ('canceled', 'canceled'), ('inprogress', 'inprogress')], default='todo', max_length=10)),
                ('constacts', models.ManyToManyField(to='contacts.contact')),
            ],
        ),
    ]
